import type { Studio } from "./types";

type Seed = Pick<Studio, "slug" | "name" | "owner" | "discipline" | "location" | "bio" | "avatar" | "hero" | "theme"> & { product: { slug: string; name: string; price: string; image: string }; collection: string; journal: string; video: string };
const seeds: Seed[] = [
  { slug: "mira-kato", name: "Mira Kato", owner: "Mira Kato", discipline: "Ceramic artist & tableware designer", location: "Setagaya, Tokyo", bio: "I make quiet objects for daily rituals—thrown slowly, fired with curiosity, and meant to be used often.", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=85", hero: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1800&q=90", theme: { accent: "#bd5335", wash: "#f1e3d5", ink: "#2e221d" }, product: { slug: "low-moon-bowl", name: "Low moon bowl", price: "$96", image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=85" }, collection: "The slow table", journal: "Notes from a quieter kiln", video: "The making of a cup" },
  { slug: "kai-ward", name: "KAI/WARD", owner: "Kai Ward", discipline: "Sneaker artist & material researcher", location: "Brooklyn, New York", bio: "Sneakers for people who notice the pavement. Hand-finished colour, repairable construction, and the city written into every pair.", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=85", hero: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1800&q=90", theme: { accent: "#d7462f", wash: "#f3e1d8", ink: "#1d262a" }, product: { slug: "concrete-runner-01", name: "Concrete runner, 01", price: "$220", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85" }, collection: "Sneaker drops", journal: "The city leaves a mark", video: "Painting a pair from scratch" },
  { slug: "ayo-femi", name: "Ayo Femi", owner: "Ayo Femi", discipline: "Painter & archive builder", location: "Lagos, Nigeria", bio: "I paint imagined archives: faces, rooms, and futures that deserve to be remembered before they disappear.", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=85", hero: "https://images.unsplash.com/photo-1577083552431-6e5fd01988f7?auto=format&fit=crop&w=1800&q=90", theme: { accent: "#a7472d", wash: "#f0ded0", ink: "#35231e" }, product: { slug: "memory-in-blue", name: "Memory in blue", price: "$460", image: "https://images.unsplash.com/photo-1577083552431-6e5fd01988f7?auto=format&fit=crop&w=700&q=85" }, collection: "An imagined archive", journal: "Painting what cannot be photographed", video: "A painting begins with listening" },
  { slug: "room-service", name: "Room Service", owner: "Lena Rose", discipline: "Home decor creator", location: "London, United Kingdom", bio: "Objects for rooms with stories already in them. I design soft lighting, useful surfaces, and a little more atmosphere.", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=85", hero: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1800&q=90", theme: { accent: "#8a6b3e", wash: "#eee6d8", ink: "#39352a" }, product: { slug: "late-afternoon-lamp", name: "Late afternoon lamp", price: "$310", image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=85" }, collection: "Rooms for lingering", journal: "How a room learns your habits", video: "Finding the right shade of light" },
  { slug: "nora-wilde", name: "Nora Wilde", owner: "Nora Wilde", discipline: "Woodworker", location: "Copenhagen, Denmark", bio: "Furniture with a soft edge, made from patient timber and the belief that the useful should also be quietly beautiful.", avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=300&q=85", hero: "https://images.unsplash.com/photo-1541971875076-8f970d573be6?auto=format&fit=crop&w=1800&q=90", theme: { accent: "#8b5534", wash: "#e8ded1", ink: "#31251e" }, product: { slug: "soft-edge-stool", name: "Soft edge stool", price: "$380", image: "https://images.unsplash.com/photo-1541971875076-8f970d573be6?auto=format&fit=crop&w=700&q=85" }, collection: "Wood collection", journal: "A chair begins with a plank", video: "Shaping a soft edge" },
  { slug: "saanvi-studio", name: "Saanvi Studio", owner: "Saanvi Mehta", discipline: "Resin & textile artist", location: "Jaipur, India", bio: "Colour found in the everyday, then held still in resin, cloth, and small luminous objects.", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=85", hero: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1800&q=90", theme: { accent: "#ad5b66", wash: "#f1dde0", ink: "#3a2630" }, product: { slug: "monsoon-resin-tray", name: "Monsoon resin tray", price: "$118", image: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=700&q=85" }, collection: "Monsoon colour studies", journal: "The colour of rain on stone", video: "Pouring colour slowly" }
];

function makeStudio(seed: Seed, index: number): Studio { const collectionSlug = seed.collection.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/, ""); const journalSlug = seed.journal.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/, ""); const videoSlug = seed.video.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/, ""); return { ...seed, socials: [{ label: "Instagram", href: "https://instagram.com" }, { label: "Website", href: `/studios/${seed.slug}` }, { label: "Pinterest", href: "https://pinterest.com" }], stats: [{ value: `${8 + index * 2}.${index + 2}k`, label: "followers" }, { value: `${180 + index * 31}`, label: "following" }, { value: `${24 + index * 7}`, label: "works collected" }], portfolio: [{ title: "Material study", image: seed.hero, size: "tall" }, { title: "A world in progress", image: seed.product.image, size: "wide" }, { title: "Detail, up close", image: seed.hero, size: "square" }, { title: "Made by hand", image: seed.product.image, size: "tall" }], products: [seed.product, { slug: `${seed.product.slug}-small`, name: `${seed.product.name}, small study`, price: `$${Math.max(48, 68 + index * 21)}`, image: seed.product.image }, { slug: `${seed.product.slug}-edition`, name: `${seed.product.name}, edition`, price: `$${Math.max(74, 96 + index * 34)}`, image: seed.hero }], collections: [{ name: seed.collection, note: `A focused series from ${seed.name}.`, image: seed.hero, slug: collectionSlug }], journal: [{ title: seed.journal, date: "12 June 2026", image: seed.product.image, slug: journalSlug }], videos: [{ title: seed.video, duration: "03:24", image: seed.hero, slug: videoSlug }], achievement: "Selected for the StudioVerse edit of independent makers to watch.", review: { quote: "The work has a presence that grows more generous with time.", name: "Nami O.", role: "Collector" }, event: { title: "Open studio gathering", date: "03 Aug · 14:00–18:00", place: seed.location } }; }
export const studios = seeds.map(makeStudio);
export function getStudio(slug: string) { return studios.find(studio => studio.slug === slug); }
