import { products } from "@/features/products/data";
import { studios } from "@/features/studios/data";
import { collections, articles, reels } from "@/features/content/data";
import type { CartLine } from "@/features/products/types";

type Order = { id: string; userId: string; lines: CartLine[]; status: string; total: number; createdAt: string; shippingAddress?: Record<string, string> };
type Message = { id: string; threadId: string; senderId: string; body: string; createdAt: string };
type CustomRequest = { id: string; userId: string; studioSlug: string; description: string; budget?: string; deadline?: string; notes?: string; status: string; createdAt: string };
const carts = new Map<string, CartLine[]>(); const wishlists = new Map<string, Set<string>>(); const orders: Order[] = []; const messages: Message[] = [{ id: "message-welcome", threadId: "mira-demo", senderId: "mira-kato", body: "Hello — thank you for spending time with the work.", createdAt: new Date().toISOString() }]; const requests: CustomRequest[] = [];
const id = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;
export const mockBackend = {
  catalog: { studios: () => studios, studio: (slug: string) => studios.find(item => item.slug === slug), products: () => products, product: (slug: string) => products.find(item => item.slug === slug), collections: () => collections, articles: () => articles, reels: () => reels },
  cart: { list: (userId: string) => carts.get(userId) ?? [], add: (userId: string, line: CartLine) => { const current = carts.get(userId) ?? []; const match = current.find(item => item.id === line.id); const next = match ? current.map(item => item.id === line.id ? { ...item, quantity: item.quantity + line.quantity } : item) : [...current, line]; carts.set(userId, next); return next; }, update: (userId: string, id: string, quantity: number) => { const next = (carts.get(userId) ?? []).flatMap(item => item.id === id && quantity < 1 ? [] : item.id === id ? [{ ...item, quantity }] : [item]); carts.set(userId, next); return next; }, remove: (userId: string, id: string) => { const next = (carts.get(userId) ?? []).filter(item => item.id !== id); carts.set(userId, next); return next; } },
  wishlist: { list: (userId: string) => [...(wishlists.get(userId) ?? new Set())], toggle: (userId: string, slug: string) => { const items = wishlists.get(userId) ?? new Set<string>(); items.has(slug) ? items.delete(slug) : items.add(slug); wishlists.set(userId, items); return [...items]; } },
  orders: { list: (userId: string) => orders.filter(order => order.userId === userId), create: (userId: string, shippingAddress?: Record<string, string>) => { const lines = carts.get(userId) ?? []; if (!lines.length) throw new Error("Cart is empty"); const order = { id: id("order"), userId, lines, status: "PENDING", total: lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0), createdAt: new Date().toISOString(), shippingAddress }; orders.unshift(order); carts.set(userId, []); return order; } },
  messages: { list: (threadId: string) => messages.filter(message => message.threadId === threadId), send: (threadId: string, senderId: string, body: string) => { const message = { id: id("message"), threadId, senderId, body, createdAt: new Date().toISOString() }; messages.push(message); return message; } },
  requests: { list: (studioSlug?: string) => studioSlug ? requests.filter(request => request.studioSlug === studioSlug) : requests, create: (userId: string, value: Omit<CustomRequest, "id" | "userId" | "status" | "createdAt">) => { const request = { ...value, id: id("request"), userId, status: "NEW", createdAt: new Date().toISOString() }; requests.unshift(request); return request; } },
  notifications: (userId: string) => [{ id: "notification-1", userId, type: "FOLLOW", text: "Ari M. started following Mira Kato", read: false, createdAt: new Date().toISOString() }, { id: "notification-2", userId, type: "ORDER", text: "Your saved collection has a new work", read: false, createdAt: new Date().toISOString() }]
};
