"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import type { CartLine } from "@/features/products/types";

type Order = { id: string; date: string; status: "Processing" | "Shipped" | "Delivered"; total: number; lines: CartLine[]; tracking: string };
type MockContext = { wishlist: string[]; toggleWishlist: (slug: string) => void; orders: Order[]; createOrder: (lines: CartLine[]) => Order; notice: string; setNotice: (notice: string) => void };
const Context = createContext<MockContext | null>(null);
export function MockProvider({ children }: { children: React.ReactNode }) { const [wishlist, setWishlist] = useState<string[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [notice, setNotice] = useState(""); useEffect(() => { const saved = localStorage.getItem("studioverse-mock"); if (saved) { const parsed = JSON.parse(saved); setWishlist(parsed.wishlist || []); setOrders(parsed.orders || []); } }, []); useEffect(() => { localStorage.setItem("studioverse-mock", JSON.stringify({ wishlist, orders })); }, [wishlist, orders]); const value = useMemo(() => ({ wishlist, toggleWishlist: (slug: string) => setWishlist(current => current.includes(slug) ? current.filter(item => item !== slug) : [...current, slug]), orders, createOrder: (lines: CartLine[]) => { const order = { id: `SV-${Math.floor(10000 + Math.random() * 89999)}`, date: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), status: "Processing" as const, total: lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0) + 18, lines, tracking: "Available when your Studio dispatches this work" }; setOrders(current => [order, ...current]); return order; }, notice, setNotice }), [wishlist, orders, notice]); return <Context.Provider value={value}>{children}{notice && <button onClick={() => setNotice("")} className="fixed bottom-5 right-5 z-50 rounded-2xl bg-ink px-5 py-3 text-sm text-canvas shadow-soft">{notice} ×</button>}</Context.Provider>; }
export function useMock() { const value = useContext(Context); if (!value) throw new Error("useMock must be used inside MockProvider"); return value; }
