"use client";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { CartLink } from "@/components/layout/cart-link";
const navItems = [{ label: "Explore", href: "/explore" }, { label: "Categories", href: "/categories" }, { label: "Community", href: "/community" }, { label: "Search", href: "/search" }, { label: "Saved", href: "/wishlist" }];
function MenuIcon({ open }: { open: boolean }) { return open ? <span aria-hidden className="text-xl leading-none">×</span> : <span aria-hidden className="flex w-4 flex-col gap-1"><i className="h-px w-full bg-current" /><i className="h-px w-full bg-current" /><i className="h-px w-full bg-current" /></span>; }
export function Navigation() { const [open, setOpen] = useState(false); return <header className="sticky top-0 z-30 border-b border-line/60 bg-canvas/90 backdrop-blur-xl"><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8" aria-label="Main navigation"><Link href="/" className="font-display text-2xl tracking-tight">StudioVerse<span className="text-accent">.</span></Link><div className="hidden items-center gap-7 md:flex">{navItems.map(item => <Link className="text-sm text-muted transition hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent" href={item.href} key={item.label}>{item.label}</Link>)}</div><div className="flex items-center gap-2"><Link href="/notifications" aria-label="Notifications" className="grid h-10 w-10 place-items-center rounded-full border border-line text-sm transition hover:bg-ink/5"><span aria-hidden>●</span></Link><div className="hidden sm:block"><CartLink /></div><ThemeToggle /><Button asChild className="hidden sm:inline-flex" size="sm"><Link href="/studio-os">Studio OS</Link></Button><button aria-expanded={open} aria-label="Open navigation" onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center rounded-full border border-line md:hidden"><MenuIcon open={open} /></button></div></nav>{open && <div className="border-t border-line bg-canvas px-5 py-5 md:hidden"><div className="grid gap-2">{navItems.map(item => <Link onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 text-sm hover:bg-ink/5" href={item.href} key={item.label}>{item.label}</Link>)}<Link onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 text-sm hover:bg-ink/5" href="/notifications">Notifications</Link><Link onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 text-sm hover:bg-ink/5" href="/cart">Cart</Link><Link onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 text-sm hover:bg-ink/5" href="/messages">Messages</Link><Link onClick={() => setOpen(false)} className="rounded-xl bg-ink px-3 py-3 text-sm text-canvas" href="/studio-os">Open Studio OS</Link></div></div>}</header>; }
