import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import type { Studio } from "@/features/studios/types";

function Arrow() { return <span aria-hidden="true">↗</span>; }
function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: string }) { return <div className="flex items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--studio-accent)]">{eyebrow}</p><h2 className="mt-3 font-display text-4xl leading-none sm:text-5xl">{title}</h2></div>{action && <Link href="#" className="shrink-0 text-sm underline decoration-1 underline-offset-4 hover:text-[var(--studio-accent)]">{action} <Arrow /></Link>}</div>; }

export function StudioPage({ studio }: { studio: Studio }) {
  return <main style={{ "--studio-accent": studio.theme.accent, "--studio-wash": studio.theme.wash, "--studio-ink": studio.theme.ink } as React.CSSProperties} className="overflow-hidden bg-canvas [--studio-accent:#bd5335]">
    <section className="relative isolate min-h-[680px] text-white">
      <Image src={studio.hero} alt={`Ceramic work by ${studio.name}`} fill priority sizes="100vw" className="-z-20 object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-t from-black/65 via-black/15 to-black/25" />
      <div className="mx-auto flex min-h-[680px] max-w-7xl flex-col px-5 pb-9 pt-6 lg:px-8">
        <div className="flex items-center justify-between"><Link href="/explore" className="font-display text-2xl">StudioVerse<span style={{ color: studio.theme.wash }}>.</span></Link><Link href="/explore" className="text-sm text-white/85 hover:text-white">← Explore Studios</Link></div>
        <div className="mt-auto grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-white/75">{studio.discipline}</p><h1 className="max-w-3xl font-display text-6xl leading-[.88] sm:text-8xl">{studio.name}</h1></div><p className="max-w-xs text-sm leading-6 text-white/85">An independent studio making space for a slower kind of everyday.</p></div>
      </div>
    </section>

    <section className="relative mx-auto max-w-7xl px-5 lg:px-8"><div className="relative -mt-10 grid gap-8 rounded-[2rem] bg-canvas px-6 py-8 shadow-soft sm:px-10 lg:grid-cols-[1.2fr_1fr_auto] lg:items-center">
      <div className="flex items-center gap-5"><Image src={studio.avatar} alt={studio.owner} width={88} height={88} className="h-[72px] w-[72px] rounded-full object-cover" /><div><div className="flex items-center gap-2"><p className="font-display text-3xl">{studio.owner}</p><span title="Verified studio" className="grid h-5 w-5 place-items-center rounded-full bg-[var(--studio-accent)] text-[10px] text-white">✓</span></div><p className="mt-1 text-sm text-muted">Verified Studio · {studio.location}</p></div></div>
      <div className="flex gap-5 border-y border-line py-5 lg:border-y-0 lg:border-l lg:pl-8 lg:py-0">{studio.stats.map(stat => <div key={stat.label}><p className="font-display text-2xl">{stat.value}</p><p className="text-xs text-muted">{stat.label}</p></div>)}</div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm">Share</Button><Button size="sm" className="bg-[var(--studio-ink)] hover:opacity-85">Follow</Button></div>
    </div></section>

    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--studio-accent)]">About the studio</p><p className="mt-5 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">{studio.bio}</p></div><div className="lg:pt-11"><p className="text-sm leading-7 text-muted">Working from a small sunlit studio in {studio.location}, Mira explores the tension between soft, irregular silhouettes and the simple ceremony of putting food on a table.</p><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2">{studio.socials.map(social => <Link className="text-sm underline underline-offset-4 hover:text-[var(--studio-accent)]" href={social.href} key={social.label}>{social.label} <Arrow /></Link>)}</div><Button className="mt-9 bg-[var(--studio-accent)] hover:opacity-90">Request a custom creation <Arrow /></Button></div></section>

    <section className="border-y border-line bg-[var(--studio-wash)]/55 py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Selected work" title="Portfolio" action="View full archive" /><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-6">{studio.portfolio.map((item, index) => <figure key={item.title} className={index === 1 ? "col-span-2" : ""}><div className={`relative overflow-hidden rounded-3xl ${item.size === "tall" ? "aspect-[.72]" : item.size === "wide" ? "aspect-[1.65]" : "aspect-square"}`}><Image src={item.image} alt={item.title} fill sizes="(max-width: 768px) 50vw, 25vw" className="object-cover transition duration-700 hover:scale-105" /></div><figcaption className="mt-3 text-sm italic text-muted">{item.title}</figcaption></figure>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionTitle eyebrow="Available now" title="Objects to live with" action="See all products" /><div className="mt-10 grid gap-6 sm:grid-cols-3">{studio.products.map(product => <Link href={product.slug ? `/products/${product.slug}` : "#"} key={product.name} className="group"><div className="relative aspect-[.85] overflow-hidden rounded-3xl bg-[var(--studio-wash)]"><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 90vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /></div><div className="mt-4 flex justify-between gap-4"><h3 className="font-display text-2xl">{product.name}</h3><p className="pt-1 text-sm text-muted">{product.price}</p></div></Link>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="relative overflow-hidden rounded-[2rem] bg-[var(--studio-ink)] text-white"><Image src={studio.collections[0].image} alt="The slow table collection" fill sizes="100vw" className="object-cover opacity-45" /><div className="relative grid min-h-[480px] content-end p-7 sm:p-12"><p className="text-xs font-semibold uppercase tracking-[.18em] text-white/70">Collection</p><h2 className="mt-3 font-display text-5xl sm:text-7xl">{studio.collections[0].name}</h2><p className="mt-3 text-white/80">{studio.collections[0].note}</p><Link href="#" className="mt-8 w-fit rounded-full border border-white/50 px-5 py-3 text-sm hover:bg-white hover:text-[var(--studio-ink)]">Enter the collection <Arrow /></Link></div></div></section>

    <section className="border-t border-line py-24"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow="Studio Journal" title="From the worktable" /><article className="mt-9 grid gap-5 sm:grid-cols-[.8fr_1fr]"><div className="relative aspect-square overflow-hidden rounded-3xl"><Image src={studio.journal[0].image} alt="Journal entry" fill sizes="(max-width: 640px) 90vw, 35vw" className="object-cover" /></div><div className="flex flex-col justify-center"><p className="text-xs text-muted">{studio.journal[0].date}</p><h3 className="mt-3 font-display text-3xl">{studio.journal[0].title}</h3><Link href="#" className="mt-5 text-sm underline underline-offset-4">Read entry <Arrow /></Link></div></article></div><div><SectionTitle eyebrow="Moving image" title="Videos" /><div className="relative mt-9 aspect-video overflow-hidden rounded-3xl"><Image src={studio.videos[0].image} alt={studio.videos[0].title} fill sizes="(max-width: 1024px) 90vw, 45vw" className="object-cover" /><div className="absolute inset-0 grid place-items-center bg-black/20"><span className="grid h-14 w-14 place-items-center rounded-full bg-white pl-1 text-[var(--studio-ink)]">▶</span></div><p className="absolute bottom-5 left-5 font-display text-2xl text-white">{studio.videos[0].title}</p><p className="absolute bottom-6 right-5 text-xs text-white">{studio.videos[0].duration}</p></div></div></div></section>

    <section className="bg-[var(--studio-ink)] py-24 text-white"><div className="mx-auto grid max-w-7xl gap-6 px-5 md:grid-cols-3 lg:px-8"><div className="rounded-3xl border border-white/15 p-7"><p className="text-xs uppercase tracking-[.18em] text-white/55">Behind the scenes</p><p className="mt-5 font-display text-3xl">A practice built around attention, touch, and use.</p><Link href="#" className="mt-8 inline-block text-sm underline underline-offset-4">Visit the workshop <Arrow /></Link></div><div className="rounded-3xl bg-white/10 p-7"><p className="text-xs uppercase tracking-[.18em] text-white/55">Achievement</p><p className="mt-5 text-lg leading-8">{studio.achievement}</p></div><blockquote className="rounded-3xl bg-[var(--studio-accent)] p-7"><p className="text-xs uppercase tracking-[.18em] text-white/70">From a collector</p><p className="mt-5 font-display text-3xl leading-tight">“{studio.review.quote}”</p><footer className="mt-6 text-sm text-white/80">{studio.review.name} · {studio.review.role}</footer></blockquote></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-10 border-b border-line pb-20 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--studio-accent)]">Next gathering</p><h2 className="mt-4 font-display text-5xl">{studio.event.title}</h2><p className="mt-5 text-muted">{studio.event.date}<br />{studio.event.place}</p><Link href="#" className="mt-7 inline-block text-sm underline underline-offset-4">RSVP to attend <Arrow /></Link></div><div className="md:pl-14"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--studio-accent)]">Stay in the orbit</p><p className="mt-4 font-display text-4xl">Follow along, or make something together.</p><div className="mt-8 flex flex-wrap gap-3"><Button className="bg-[var(--studio-ink)]">Follow {studio.name}</Button><Button variant="outline">Contact the studio</Button></div></div></div></section>
  </main>;
}
