import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Navigation } from "@/components/layout/navigation";
import { Footer } from "@/components/layout/footer";
import { collections } from "@/features/content/data";
import { formatPrice } from "@/features/products/data";
export function generateStaticParams() { return collections.map(collection => ({ slug: collection.slug })); }
export default function CollectionPage({ params }: { params: { slug: string } }) { const collection = collections.find(item => item.slug === params.slug); if (!collection) notFound(); return <><Navigation /><main className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><nav className="text-sm text-muted"><Link href="/explore">Explore</Link> <span> / </span><Link href={`/studios/${collection.studio.slug}`}>{collection.studio.name}</Link> <span> / </span>{collection.name}</nav><section className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">Collection</p><h1 className="mt-4 font-display text-6xl leading-none">{collection.name}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">{collection.story}</p><Link href={`/studios/${collection.studio.slug}`} className="mt-7 inline-block text-sm underline underline-offset-4">Visit {collection.studio.name} ↗</Link></div><div className="relative aspect-[1.2] overflow-hidden rounded-[2rem]"><Image src={collection.image} alt={collection.name} fill className="object-cover" /></div></section><section className="mt-20"><h2 className="font-display text-4xl">Works in this collection</h2><div className="mt-7 grid gap-5 sm:grid-cols-3">{collection.products.map(product => <Link href={`/products/${product.slug}`} key={product.slug} className="group"><div className="relative aspect-[.9] overflow-hidden rounded-3xl"><Image src={product.gallery[0]} alt={product.name} fill className="object-cover transition group-hover:scale-105" /></div><div className="mt-3 flex justify-between"><h3 className="font-display text-2xl">{product.name}</h3><span className="text-sm text-muted">{formatPrice(product.price)}</span></div></Link>)}</div></section></main><Footer /></>; }
