"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { CartLine } from "@/features/products/types";
export type MockOrder = { id: string; lines: CartLine[]; status: "Pending" | "Accepted" | "Completed" | "Cancelled"; createdAt: string; delivery: string; total: number };
export type CustomRequest = { id: string; studio: string; description: string; budget: string; deadline: string; notes: string; status: "New" | "Accepted" | "Declined" };
type Store = { lines: CartLine[]; saved: CartLine[]; wishlist: string[]; orders: MockOrder[]; requests: CustomRequest[]; hydrated: boolean; count: number; addLine: (line: CartLine) => void; updateQuantity: (id: string, quantity: number) => void; removeLine: (id: string) => void; saveForLater: (id: string) => void; moveToCart: (id: string) => void; toggleWishlist: (slug: string) => void; clearCart: () => void; placeOrder: () => MockOrder | undefined; submitRequest: (request: Omit<CustomRequest, "id" | "status">) => void };
const StoreContext = createContext<Store | null>(null); const key = "studioverse-mvp-store";
export function CartProvider({ children }: { children: React.ReactNode }) { const [lines, setLines] = useState<CartLine[]>([]); const [saved, setSaved] = useState<CartLine[]>([]); const [wishlist, setWishlist] = useState<string[]>([]); const [orders, setOrders] = useState<MockOrder[]>([]); const [requests, setRequests] = useState<CustomRequest[]>([]); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { let active = true; (async () => { try { const state = JSON.parse(window.localStorage.getItem(key) ?? "{}"); if (active) { setLines(state.lines ?? []); setSaved(state.saved ?? []); setWishlist(state.wishlist ?? []); setOrders(state.orders ?? []); setRequests(state.requests ?? []); } const [cartResponse, wishlistResponse] = await Promise.all([fetch("/api/cart"), fetch("/api/wishlist")]); const cart = await cartResponse.json(); const wishlistData = await wishlistResponse.json(); if (active && cartResponse.ok) setLines(cart.data ?? []); if (active && wishlistResponse.ok) setWishlist(wishlistData.data ?? []); } catch { /* Keep the cache for offline development. */ } finally { if (active) setHydrated(true); } })(); return () => { active = false; }; }, []);
  useEffect(() => { if (hydrated) window.localStorage.setItem(key, JSON.stringify({ lines, saved, wishlist, orders, requests })); }, [hydrated, lines, saved, wishlist, orders, requests]);
  const addLine = useCallback((line: CartLine) => { setLines(current => { const found = current.find(item => item.productSlug === line.productSlug); return found ? current.map(item => item.productSlug === line.productSlug ? { ...item, quantity: item.quantity + line.quantity } : item) : [...current, line]; }); void fetch("/api/cart", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(line) }).then(response => response.ok ? response.json() : undefined).then(result => result?.data && setLines(result.data)).catch(() => undefined); }, []);
  const updateQuantity = useCallback((id: string, quantity: number) => { setLines(current => quantity < 1 ? current.filter(item => item.id !== id) : current.map(item => item.id === id ? { ...item, quantity } : item)); void fetch("/api/cart", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, quantity }) }).then(response => response.ok ? response.json() : undefined).then(result => result?.data && setLines(result.data)).catch(() => undefined); }, []);
  const removeLine = useCallback((id: string) => { setLines(current => current.filter(item => item.id !== id)); void fetch(`/api/cart?id=${encodeURIComponent(id)}`, { method: "DELETE" }).then(response => response.ok ? response.json() : undefined).then(result => result?.data && setLines(result.data)).catch(() => undefined); }, []);
  const saveForLater = useCallback((id: string) => { setLines(current => { const item = current.find(line => line.id === id); if (item) setSaved(savedLines => [...savedLines.filter(line => line.id !== id), item]); return current.filter(line => line.id !== id); }); }, []);
  const moveToCart = useCallback((id: string) => { setSaved(current => { const item = current.find(line => line.id === id); if (item) addLine(item); return current.filter(line => line.id !== id); }); }, [addLine]);
  const toggleWishlist = useCallback((slug: string) => { setWishlist(current => current.includes(slug) ? current.filter(item => item !== slug) : [...current, slug]); void fetch("/api/wishlist", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productSlug: slug }) }).then(response => response.ok ? response.json() : undefined).then(result => result?.data && setWishlist(result.data)).catch(() => undefined); }, []);
  const placeOrder = useCallback(() => { if (!lines.length) return undefined; const total = lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0); const order = { id: `SV-${Math.random().toString(36).slice(2, 7).toUpperCase()}`, lines, status: "Pending" as const, createdAt: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), delivery: "Estimated delivery in 7–12 days", total }; setOrders(current => [order, ...current]); setLines([]); return order; }, [lines]);
  const submitRequest = useCallback((request: Omit<CustomRequest, "id" | "status">) => setRequests(current => [{ ...request, id: `CR-${Date.now().toString().slice(-5)}`, status: "New" }, ...current]), []);
  const value = useMemo(() => ({ lines, saved, wishlist, orders, requests, hydrated, count: lines.reduce((total, line) => total + line.quantity, 0), addLine, updateQuantity, removeLine, saveForLater, moveToCart, toggleWishlist, clearCart: () => setLines([]), placeOrder, submitRequest }), [lines, saved, wishlist, orders, requests, hydrated, addLine, updateQuantity, removeLine, saveForLater, moveToCart, toggleWishlist, placeOrder, submitRequest]); return <StoreContext.Provider value={value}>{children}</StoreContext.Provider>; }
export function useCart() { const value = useContext(StoreContext); if (!value) throw new Error("useCart must be used inside CartProvider"); return value; }
