"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { dashboardSections } from "@/features/dashboard/data";
import { useMock } from "@/features/commerce/mock-provider";
type ProductRow = { id: number; name: string; status: "Published" | "Draft"; price: string };
const initialProducts: ProductRow[] = [{ id: 1, name: "Low moon bowl", status: "Published", price: "$280" }, { id: 2, name: "Pebble pitcher", status: "Draft", price: "$160" }];
function Card({ children }: { children: React.ReactNode }) { return <section className="rounded-3xl border border-line bg-canvas p-5 shadow-card">{children}</section>; }
export function StudioOS() { const [active, setActive] = useState("Overview"); const [products, setProducts] = useState(initialProducts); const [editing, setEditing] = useState<ProductRow | null>(null); const [saved, setSaved] = useState(false); const { setNotice } = useMock(); const groups = [...new Set(dashboardSections.map(item => item.group))]; const remove = (id: number) => { setProducts(rows => rows.filter(row => row.id !== id)); setNotice("Product removed from your Studio"); }; const publish = (id: number) => { setProducts(rows => rows.map(row => row.id === id ? { ...row, status: "Published" } : row)); setNotice("Product published"); };
  return <main className="min-h-screen bg-[#f7f5ef]"><div className="mx-auto flex max-w-[1500px]"><aside className="sticky top-0 hidden h-screen w-64 shrink-0 border-r border-line bg-canvas p-5 lg:block"><p className="font-display text-2xl">Studio OS<span className="text-accent">.</span></p><p className="mt-1 text-xs text-muted">Mira Kato Studio</p><nav className="mt-8 space-y-5">{groups.map(group => <div key={group}><p className="px-3 text-[10px] font-semibold uppercase tracking-[.16em] text-muted">{group}</p>{dashboardSections.filter(item => item.group === group).map(item => <button onClick={() => setActive(item.label)} className={`mt-1 w-full rounded-xl px-3 py-2 text-left text-sm ${active === item.label ? "bg-ink text-canvas" : "text-muted hover:bg-ink/5 hover:text-ink"}`} key={item.label}>{item.label}</button>)}</div>)}</nav></aside><div className="min-w-0 flex-1"><header className="flex h-20 items-center justify-between border-b border-line px-5 lg:px-10"><div><p className="text-xs text-muted">Studio OS / {active}</p><p className="font-display text-xl lg:hidden">Mira Kato</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setNotice("Search opened — try a product or collector name")}>Search</Button><Button size="sm" onClick={() => setActive("Products")}>Add work</Button></div></header><section className="px-5 py-9 lg:px-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">Mira Kato Studio</p><h1 className="mt-3 font-display text-5xl">{active}</h1><div className="mt-8">{active === "Overview" ? <Overview setActive={setActive} /> : active === "Products" ? <Products products={products} editing={editing} setEditing={setEditing} publish={publish} remove={remove} /> : active === "Orders" ? <Orders /> : ["Customization Requests", "Commission Requests"].includes(active) ? <Requests type={active} /> : active === "Settings" ? <Settings saved={saved} save={() => { setSaved(true); setNotice("Studio settings saved"); }} /> : active === "Collections" ? <Collections /> : <Workspace title={active} />}</div></section></div></div>{editing && <ProductEditor product={editing} close={() => setEditing(null)} save={(value) => { setProducts(rows => rows.map(row => row.id === value.id ? value : row)); setEditing(null); setNotice("Product changes saved"); }} />}</main>; }
function Overview({ setActive }: { setActive: (value: string) => void }) { return <><div className="grid gap-4 sm:grid-cols-3"><Metric label="This month" value="$4,860" note="18% above last month" /><Metric label="New followers" value="38" note="Your story is travelling" /><Metric label="Open requests" value="03" note="Need a response" /></div><Card><h2 className="font-display text-3xl">Run the work, not just the shop.</h2><p className="mt-3 text-sm text-muted">Everything from your Studio, in one place.</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => setActive("Products")}>Manage products</Button><Button variant="outline" onClick={() => setActive("Customization Requests")}>Review requests</Button><Button variant="outline" onClick={() => setActive("Settings")}>Edit Studio</Button></div></Card></>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <Card><p className="text-xs text-muted">{label}</p><p className="mt-3 font-display text-4xl">{value}</p><p className="mt-2 text-xs text-muted">{note}</p></Card>; }
function Products({ products, editing, setEditing, publish, remove }: { products: ProductRow[]; editing: ProductRow | null; setEditing: (p: ProductRow) => void; publish: (id: number) => void; remove: (id: number) => void }) { return <Card><div className="flex justify-between"><h2 className="font-display text-3xl">Works in your Studio</h2><Button size="sm" onClick={() => setEditing({ id: Date.now(), name: "Untitled work", status: "Draft", price: "$0" })}>Create product</Button></div><div className="mt-6 divide-y divide-line">{products.map(product => <div className="flex flex-wrap items-center justify-between gap-4 py-4" key={product.id}><div><p className="font-medium">{product.name}</p><p className="mt-1 text-xs text-muted">{product.price} · {product.status}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(product)}>Edit</Button>{product.status === "Draft" && <Button size="sm" onClick={() => publish(product.id)}>Publish</Button>}<button className="text-sm text-accent" onClick={() => remove(product.id)}>Delete</button></div></div>)}</div></Card>; }
function ProductEditor({ product, close, save }: { product: ProductRow; close: () => void; save: (p: ProductRow) => void }) { const [value, setValue] = useState(product); return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-5"><form onSubmit={e => { e.preventDefault(); save(value); }} className="w-full max-w-lg rounded-3xl bg-canvas p-6"><h2 className="font-display text-3xl">{product.id === Date.now() ? "Create product" : "Edit product"}</h2><input value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} className="mt-6 h-11 w-full rounded-xl border border-line bg-transparent px-3" /><input value={value.price} onChange={e => setValue({ ...value, price: e.target.value })} className="mt-4 h-11 w-full rounded-xl border border-line bg-transparent px-3" /><div className="mt-6 flex justify-between"><Button variant="outline" type="button" onClick={close}>Cancel</Button><Button>Save draft</Button></div></form></div>; }
function Orders() { const [state, setState] = useState(["Pending", "Accepted", "Completed"]); return <Card><h2 className="font-display text-3xl">Orders to shape and send</h2><div className="mt-6 space-y-3">{state.map((status, index) => <div key={index} className="flex justify-between rounded-2xl bg-ink/[.035] p-4"><span>SV-104{index + 1} · Collector order</span><button onClick={() => setState(rows => rows.map((item, i) => i === index ? item === "Pending" ? "Accepted" : item === "Accepted" ? "Completed" : "Cancelled" : item))} className="text-sm text-accent">{status} → advance</button></div>)}</div></Card>; }
function Requests({ type }: { type: string }) { const [accepted, setAccepted] = useState(false); return <Card><h2 className="font-display text-3xl">A new brief from Lena Rose</h2><p className="mt-3 text-sm leading-6 text-muted">A low, wide serving bowl in soft sage for a table of six. Budget $420. Needed by 12 August.</p><p className="mt-4 rounded-xl bg-ink/[.04] p-3 text-sm">Reference images: 3 uploaded · Notes: “Organic rim, no glaze shine.”</p><div className="mt-6 flex gap-3"><Button onClick={() => setAccepted(true)}>{accepted ? "Accepted — message sent" : "Accept request"}</Button><Button variant="outline">Request details</Button></div><p className="mt-5 text-xs text-muted">This request appears in your messages and order workspace after acceptance.</p></Card>; }
function Collections() { return <Workspace title="Collections" body="Create and arrange the chapters visitors move through in your Studio." />; }
function Settings({ saved, save }: { saved: boolean; save: () => void }) { return <Card><h2 className="font-display text-3xl">Studio settings</h2><div className="mt-6 grid gap-4"><input defaultValue="Mira Kato Studio" className="h-11 rounded-xl border border-line bg-transparent px-3" /><textarea defaultValue="Ceramic objects for rituals around the table." className="min-h-24 rounded-xl border border-line bg-transparent p-3" /><input defaultValue="instagram.com/mirakato" className="h-11 rounded-xl border border-line bg-transparent px-3" /><select className="h-11 rounded-xl border border-line bg-transparent px-3"><option>Warm gallery theme</option><option>Dark studio theme</option></select><label className="text-sm"><input type="checkbox" defaultChecked className="mr-2" />Show contact link</label></div><Button onClick={save} className="mt-6">{saved ? "Saved" : "Save Studio changes"}</Button></Card>; }
function Workspace({ title, body }: { title: string; body?: string }) { return <Card><h2 className="font-display text-3xl">{title} workspace</h2><p className="mt-3 text-sm leading-6 text-muted">{body ?? `Manage your Studio’s ${title.toLowerCase()} from this connected mock workspace.`}</p><Button className="mt-6" onClick={() => window.alert(`${title} action completed in demo mode.`)}>Create or update</Button></Card>; }
